Add ability to patch kustomize patches before checking back into gitops repo

diff --git a/kube/tekton/tasks/argo/patch-config-repo.yaml b/kube/tekton/tasks/argo/patch-config-repo.yaml
--- a/kube/tekton/tasks/argo/patch-config-repo.yaml
+++ b/kube/tekton/tasks/argo/patch-config-repo.yaml
@@ -38,7 +38,7 @@ spec:
         git checkout -b ${BRANCH_NAME}
 
         echo ${BRANCH_NAME} | tr -d "\n" | tee $(results.branch-name.path)
-    - name: update-deployment
+    - name: update-image
       workingDir: $(workspaces.input.path)/$(params.PATH_CONTEXT)
       image: quay.io/eformat/openshift-kustomize:latest
       script: |
@@ -55,6 +55,28 @@ spec:
 
         kustomize edit set image payment/image="$(resources.inputs.app-image.url):$(params.IMAGE_TAG)"
         echo -e "Contents after image kustomization are:\n $(cat ${KUSTOMIZE_FILE})"
+    - name: update-patches
+      workingDir: $(workspaces.input.path)/$(params.PATH_CONTEXT)
+      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
+      script: |
+        #!/usr/bin/env bash
+
+        set -Eeuo pipefail
+
+        PATCH_FILE=cm-patch.yaml
+        if [[ ! -f ${PATCH_FILE} ]]; then
+          echo "ERROR: Could not find ${PATCH_FILE} at $(pwd)."
+          exit 1
+        fi
+        
+        PATCH_CONTENTS=$(cat ${PATCH_FILE})
+        echo "Contents of $(pwd)/${PATCH_FILE} are: ${PATCH_CONTENTS}"
+
+        echo "Adding suffix to topic names representing this build"
+        # remove -PATCH with the current image_tag (build number)
+        sed -i.bak "s/-PATCH/-$(params.IMAGE_TAG)/g" cm-patch.yaml
+
+        echo -e "Contents after are: $(cat ${PATCH_FILE})\n"
     - name: checkin
       workingDir: $(workspaces.input.path)/$(params.PATH_CONTEXT)
       volumeMounts:
